### ISSUE TITLE
Description Field should be split into multiple fields

### ISSUE THREAD

**Issue by fox2mike** [rtucker-mozilla/WhistlePig#33]
When we take a look at our maint notification, we have :
1. Short Summary
2. Details
3. Impact of Work
4. What will be Impacted

An example is at https://status.mozilla.org/en-US/detail/9/

I'm wondering if it makes sense to split up the Description field into these sub-fields and having that information presented appropriately, over email or on the webpage.

Thoughts?

**Comment by rtucker-mozilla** [comment]
We have summary and description. I could re title them as you've suggested.

I can add a new field for impact of work.

We have the what will be affected in the service outages section.

Sound good?

**Comment by fox2mike** [comment]
I guess that works! 

And in the email templates, we can have the short summary and details sections before the rest too.

**Comment by rtucker-mozilla** [comment]
You can update the email template however you want it to look, that's the point :)

**Comment by fox2mike** [comment]
Truth. As long as I can have the << >> sections....I guess they'll get autofilled.

**Comment by rtucker-mozilla** [comment]
That's a big 10-4 little buddy

**Comment by rtucker-mozilla** [comment]
alter table whistlepig_statusupdate add column impact_of_work text;

**Comment by rtucker-mozilla** [comment]
alter table whistlepig_statusupdate add column end_time datetime;

**Comment by rtucker-mozilla** [comment]
alter table whistlepig_statusupdate add column frontpage int

This will allow us to control which notifications are active on the homepage, so we can manually remove unnecessary updates.

**Comment by rtucker-mozilla** [comment]
Pushed this out and tested, looks good to me.
