### ISSUE TITLE
Multiple Bug IDs entered show up as a single URL link

### ISSUE THREAD

**Issue by fox2mike** [rtucker-mozilla/WhistlePig#36]
For example, look at https://status.mozilla.org/en-US/detail/14/

This has 2 bugs listed and the URL is https://bugzilla.mozilla.org/show_bug.cgi?id=840029,%20807414 when it should be https://bugzilla.mozilla.org/show_bug.cgi?id=840029 and https://bugzilla.mozilla.org/show_bug.cgi?id=807414

Thanks!

**Comment by rtucker-mozilla** [comment]
This has been tested and deployed.
