### ISSUE TITLE
<<type of work>> doesn't get filled in automatically in the email template

### ISSUE THREAD

**Issue by fox2mike** [rtucker-mozilla/WhistlePig#38]
I'm not sure where this value should be populated from, but right now it always remains <<type of work>> when we try to create an outage notification.

**Comment by rtucker-mozilla** [comment]
Since the template is editable, you can simply edit the template to not include this line.
Another option would be to add a type_of_work field.

Which would you prefer?

**Comment by fox2mike** [comment]
I think we should have an editable type of work field. Thanks!

## 

Shyam Mani
Mozilla 
http://www.mozilla.org/

**Comment by rtucker-mozilla** [comment]
Going to close this out as unnecessary, atleast for the time being. We can easily implement later if necessary.
