### ISSUE TITLE
offer readonly ICS data feed

### ISSUE THREAD

**Issue by rtucker-mozilla** [rtucker-mozilla/WhistlePig#39]
Generate output for read only ICS calendar feed

**Comment by rtucker-mozilla** [comment]
This appears to be working as expected. I'm going to close this out, but will reopen if any issues arise.

**Comment by floatingatoll** [comment]
The times seem to be correct on the instance I viewed this morning, though it had no test data outside of daylight savings (PDT -7).

Could the longform description of the event be added to the DESCRIPTION field in the ics feed?

**Comment by rtucker-mozilla** [comment]
Everything seems good here. Closing out.

**Comment by fox2mike** [comment]
Can we add a public link to https://status.mozilla.org/en-US/ical/feed/ please? It's hard to find otherwise. Thanks!
