### ISSUE TITLE
end_time should be split into multiple fields

### ISSUE THREAD

**Issue by fox2mike** [rtucker-mozilla/WhistlePig#43]
Just like event_start_date and event_start_time are different. 

We have end_time currently, which is date time and that's confusing, especially when creating email from the notices.

thanks!

**Comment by rtucker-mozilla** [comment]
This can be utilized in the Outage Notification Template by:

```
<<event_end_time>>
<<event_end_date>>
```

**Comment by rtucker-mozilla** [comment]
Updated a production outage notification template with the new variables and they interpolate as expected.
