### ISSUE TITLE
Subject line changes aren't shown in GMail

### ISSUE THREAD

**Issue by justdave** [rtucker-mozilla/WhistlePig#57]
Notifications sent to Gmail about the same event get threaded together, and GMail only shows you the subject line from the first message in the thread.  If the subject line changes, you never see it.  The most visible notification of status changes was in the subject line and this is totally lost in GMail.  The tags for "UPCOMING" "STARTED" and "COMPLETED" need to be (prominently) in the body of the email if they're going to be useful at all on a GMail world.

**Comment by justdave** [comment]
For example, this morning I have a thread called "[Planned Maintenance Notification][STARTING] Vidyo routing changes" with two completely identical messages in it except the second one says "Resolved" on the issue status line buried in the machine-readable part at the bottom that most people just gloss over.

**Comment by rtucker-mozilla** [comment]
This is solved by simply editing the outage notification template to include the issue status. 
I've added the Issue Status above the short description in the template.
